# Generated by Django 5.2.6 on 2025-12-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
